#file: noinspection SpellCheckingInspection
run:
  skip-files:
    - ".*_enum\\.go$"
    - "test/*.*"
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.22'
output:
  format: colored-line-number
linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - prealloc
    - revive
    - whitespace
    - goheader
    - errcheck
    - revive
    - usestdlibvars
    - durationcheck
    - contextcheck
    - decorder
    - gocheckcompilerdirectives
    - grouper
    - musttag
    - prealloc
    - paralleltest
    - unconvert
    - wastedassign
    - nilerr
    - nilnil
linters-settings:
  revive:
    rules:
      - name: datarace
        severity: warning
        disabled: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - style
      - performance
      - opinionated
    disabled-checks:
      - exitAfterDefer
  govet:
    settings:
      printf:
        funcs:
          - (*github.com/rs/zerolog.Event).Msgf
          - github.com/pkg/errors.Errorf
          - github.com/pkg/errors.Wrapf
          - github.com/pkg/errors.WithMessagef
    enable:
      - structtag
      - unmarshal
      - ifaceassert
issues:
  exclude-rules:
    - linters:
        - gocritic
      text: "sprintfQuotedString: use %q instead of \"%s\" for quoted strings"
    - linters:
        - unused
      text: "func `readDataDescriptor` is unused"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_IFMT should be sIFMT"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_IFSOCK should be sIFSOCK"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_IFLNK should be sIFLNK"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_IFREG should be sIFREG"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_IFBLK should be sIFBLK"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_IFDIR should be sIFDIR"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_IFCHR should be sIFCHR"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_IFIFO should be sIFIFO"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_ISUID should be sISUID"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_ISGID should be sISGID"
    - linters:
        - stylecheck
      text: "ST1003: should not use underscores in Go names; const s_ISVTX should be sISVTX"
    - linters:
        - ineffassign
      text: "ineffectual assignment to length"
    - linters:
        - ineffassign
      text: "log.Fatal will exit, and `defer util.DiscardErrorOnly(static.Close())` will not run"
    - linters:
        - staticcheck
      text: "SA4006: this value of `length` is never used"
    - linters:
        - wastedassign
      text: "assigned to length, but reassigned without using the value"


