#file: noinspection SpellCheckingInspection
run:
  skip-files:
    - ".*_enum\\.go$"
    - "test/*.*"
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.22'
output:
  format: colored-line-number
linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    - dupl
    - errorlint
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - prealloc
    - revive
    - stylecheck
    - whitespace
    - goheader
    - errcheck
    - revive
    - usestdlibvars
    - durationcheck
    - contextcheck
    - decorder
    - gocheckcompilerdirectives
    - grouper
    - musttag
    - prealloc
    - paralleltest
    - unconvert
    - wastedassign
    - wrapcheck
    - nilerr
    - nilnil
linters-settings:
  revive:
    rules:
      - name: datarace
        severity: warning
        disabled: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - style
      - performance
      - opinionated
  govet:
    settings:
      printf:
        funcs:
          - (*github.com/rs/zerolog.Event).Msgf
          - github.com/pkg/errors.Errorf
          - github.com/pkg/errors.Wrapf
          - github.com/pkg/errors.WithMessagef
    enable:
      - structtag
      - unmarshal
      - ifaceassert