name: Go Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: ^1.20.2
      - run: go install github.com/abice/go-enum@latest
      - run: sudo apt install libxdo-dev
      - name: Generate
        run: go generate -v ./...
      - name: Build
        run: go build -v ./...