name: Go Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: ^1.20.2
      - run: go install github.com/abice/go-enum@latest
      - run: go install github.com/jstemmer/go-junit-report/v2@latest
      - run: apt install libxdo-dev
      - name: Generate
        run: go generate -v ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic -json -v ./... | \
          go-junit-report -parser gojson -set-exit-code > report.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: report.xml
        if: always()